[package]
name = "velax_contract"
edition = "2024.beta"

[dependencies]
# This specific subdir points ONLY to the framework, preventing the "Path too long" error
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
velax_contract = "0x0"